
!function (w, d, t) {
  w.TiktokAnalyticsObject=t;var ttq=w[t]=w[t]||[];ttq.methods=["page","track","identify","instances","debug","on","off","once","ready","alias","group","enableCookie","disableCookie"],ttq.setAndDefer=function(t,e){t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}};for(var i=0;i<ttq.methods.length;i++)ttq.setAndDefer(ttq,ttq.methods[i]);ttq.instance=function(t){for(var e=ttq._i[t]||[],i=0;i<ttq.methods.length;i++)ttq.setAndDefer(e,ttq.methods[i]);return e},ttq.load=function(e,i){var n="https://analytics.tiktok.com/i18n/pixel/events.js";ttq._i=ttq._i||{},ttq._i[e]=[],ttq._i[e]._u=n,ttq._t=ttq._t||{},ttq._t[e]=+new Date,ttq._o=ttq._o||{},ttq._o[e]=i||{};i=document.createElement("script");i.type="text/javascript",i.async=!0,i.src=n+"?sdkid="+e+"&lib="+t;e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(i,e)},ttq.legacyLoad=function(t,e){ttq._i=ttq._i||{},ttq._i[t]=[],ttq._t=ttq._t||{},ttq._t[t]=+new Date,ttq._o=ttq._o||{},ttq._o[t]=e||{},ttq._legacy=ttq._legacy||[],ttq._legacy.push(t)};


  ttq.legacyLoad('CCRH2EJC77UDPV42AVRG');
  ttq.page();
}(window, document, 'ttq');

window[window["TiktokAnalyticsObject"]]._env = {"env":"external","key":""};
window[window["TiktokAnalyticsObject"]]._variation_id = 'test_3';; if(!window[window["TiktokAnalyticsObject"]]._server_unique_id) window[window["TiktokAnalyticsObject"]]._server_unique_id = '21191a1a-e07f-11ed-918a-08c0eb4a7c76';window[window["TiktokAnalyticsObject"]]._plugins = {"AdvancedMatching":true,"AutoAdvancedMatching":true,"Callback":true,"Identify":true,"Monitor":false,"PerformanceInteraction":false,"Shopify":true,"WebFL":false};
!function(){function i(){return window&&window.TiktokAnalyticsObject||"ttq"}function t(){return window&&window[i()]}var n,o,e,a,c,r=[{id:"MTFlZGFkNDkwMA",map:{AutoAdvancedMatching:!1,Shopify:!1,Monitor:!1}},{id:"MTFlZGFkNDkwMQ",map:{AutoAdvancedMatching:!0,Shopify:!1,Monitor:!1}},{id:"MTFlZGFkNDkwMg",map:{AutoAdvancedMatching:!1,Shopify:!0,Monitor:!1}},{id:"MTFlZGFkNDkwMw",map:{AutoAdvancedMatching:!0,Shopify:!0,Monitor:!1}},{id:"MTFlZGFkNDkwNA",map:{AutoAdvancedMatching:!1,Shopify:!1,Monitor:!0}},{id:"MTFlZGFkNDkwNQ",map:{AutoAdvancedMatching:!0,Shopify:!1,Monitor:!0}},{id:"MTFlZGFkNDkwNg",map:{AutoAdvancedMatching:!1,Shopify:!0,Monitor:!0}},{id:"MTFlZGFkNDkwNw",map:{AutoAdvancedMatching:!0,Shopify:!0,Monitor:!0}}],d={"info":{"pixelCode":"CCRH2EJC77UDPV42AVRG","name":"CU Boulder - Pixel","status":0,"setupMode":0,"partner":"","advertiserID":"7148533872836280322","is_onsite":false,"firstPartyCookieEnabled":true},"plugins":{"Shopify":false,"AdvancedMatching":{"email":true,"phone_number":true},"AutoAdvancedMatching":null,"Callback":true,"Identify":true,"Monitor":true,"PerformanceInteraction":true,"WebFL":true},"rules":[{"code_id":7194926171354611713,"pixel_event_id":7194926171354611713,"trigger_type":"PAGEVIEW","conditions":[{"variable_type":"PAGE_URL","operator":"CONTAINS","value":"beboulder/thanks-connecting-us","dynamic_parameter":{"currency":"","value":"","contents":null,"value_parsing_method":0,"value_index":0}}],"code":"\n\u003cscript\u003e\nwindow[window.TiktokAnalyticsObject].instance(\"CCRH2EJC77UDPV42AVRG\").track(\"SubmitForm\",{\"pixelMethod\":\"standard\"});\n\u003c/script\u003e\n"}]},l="https://analytics.tiktok.com/i18n/pixel/static/",p=t();p||(p=[],window&&(window[i()]=p)),Object.assign(d,{options:(n=d.info.pixelCode,(o=t()._o)&&o[n]||{})}),function(i){p._i||(p._i={});var t=i.info.pixelCode;t&&(p._i[t]||(p._i[t]=[]),Object.assign(p._i[t],i),p._i[t]._load=+new Date)}(d),e=function(i,t,n){var o=0<arguments.length&&void 0!==i?i:{},e=1<arguments.length?t:void 0,t=2<arguments.length?n:void 0,n=function(i,t){for(var n=0;n<i.length;n++)if(t.call(null,i[n],n))return i[n]}(r,function(i){var t=i.map;return function(i,t){for(var n=0;n<i.length;n++)if(!t.call(null,i[n],n))return!1;return!0}(Object.keys(t),function(i){return!(!o[i]||!e[i])===t[i]})});return n?t+"main.".concat(n.id,".js"):t+"main.".concat(r[0].id,".js")}(p._plugins,d.plugins,l),a=d.info.pixelCode,(void 0!==self.DedicatedWorkerGlobalScope?self instanceof self.DedicatedWorkerGlobalScope:"DedicatedWorkerGlobalScope"===self.constructor.name)?self.importScripts&&self.importScripts(e):((c=document.createElement("script")).type="text/javascript",c.async=!0,c.src=e,c.setAttribute("data-id",a),(a=document.getElementsByTagName("script")[0])&&a.parentNode&&a.parentNode.insertBefore(c,a))}();
